version: '3.1'

services:

  api:
    build: ./api
    ports:
      - "8180:8080"
    environment:
      MICRO_ADDRESS: ":8080"

  web:
    command: web
    image: micro/micro:latest
    ports:
      - "8182:8082"
    environment:
      MICRO_ADDRESS: ":8082"

  consignment-service:
    build: ./consignment-service
    ports:
      - "50051:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    ports:
      - "50052:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
      - "50053:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats"

  email-service:
    build: ./email-service
    ports:
      - "50054:50051"
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats"

  datastore:
    image: mongo
    ports:
      - "27017:27017"

  database:
    image: postgres
    ports:
      - "5432:5432"

  nats:
    image: nats
    ports:
      - "4222:4222"