version: '3.1'

services:
  consignment-cli:
    build: ./consignment-cli
    environment:
      TOKEN: "${TOKEN}"

  user-cli:
    build: ./user-cli

  consignment-service:
    build: ./consignment-service
    environment:
      DB_HOST: "datastore:27017"

  vessel-service:
    build: ./vessel-service
    environment:
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    environment:
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats"

  email-service:
    build: ./email-service
    environment:
      MICRO_BROKER: "nats"
      MICRO_BROKER_ADDRESS: "nats"

  datastore:
    image: mongo
    ports:
      - "27017:27017"

  database:
    image: postgres
    ports:
      - "5432:5432"

  nats:
    image: nats
    ports:
      - 4222:4222